In [2]:
#1.import numpy as np and print the version number:
import numpy as np
print(np.__version__)

1.26.4


In [4]:
#2.create a 1D array of numbers from 0 to 12:
import numpy as np
arr = np.arange(13)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
#3.create a 2X3 numpy array of all trues
import numpy as np
arr= np.ones((2,3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]]


In [7]:
#4.how to extract items that satisfy a given condition from 1D array?etract all odd numbers from a 1D array
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
odd_numbers=np.where(arr % 2 == 1)
print(odd_numbers)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [12]:
#5.how to replace items that satisfy a given condition with another value in numpy array?replace all odd numbers  in arr with -1
#itemsthat satisfy a given condition with another value in numpy can replace by using boolean indexing
import numpy as np
arr =np.array([0,1,2,3,4,5,6,7,8,9])
arr [arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
#6.convert a 1D array to a 2D array with 2 rows:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
x =arr.reshape(2, -1)
print(x)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
#7.stack array a and b vertically:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b =np.array([[7,8,9],[10,11,12]])
arr =np.vstack((a,b))
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
#8.stack the arrays a and b horizontally:
import numpy as np
a =([[1,2,3],[4,5,6]])
b=([[7,8,9],[10,11,12]])
arr =np.hstack((a,b))
print(arr)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [18]:
#9.create the following pattern without hardcoding . use only numpy functions and the below input array a.
#input = np.array([1,2,3])
import numpy as np
arr =np.array([1,2,3])
x =np.repeat(arr, arr)
print(x)

[1 2 2 3 3 3]


In [20]:
#10.get a index positions where elements of a and b match:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
arr =np.where(a == b)
print(arr)


(array([2], dtype=int64),)


In [24]:
#11.swap column 1 and 2 in the array arr.
import numpy as np
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[:, [1,2]] = arr[:, [2,1]]
print(arr)


[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [26]:
#12.reverse the coloumn of a 2D array arr:
import numpy as np
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
reversed_arr = arr[:, ::-1]
print(reversed_arr)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [27]:
#13.create a 2D array of shape 5X3 to contain random decimal numbers between 5 and 10:
import numpy as np
arr =np.random.uniform(5,10, size =(5,3))
print(arr)

[[9.89072009 7.43787682 9.33207396]
 [9.58584624 8.58384481 9.49766877]
 [6.62314387 5.29195448 8.3703892 ]
 [9.97200458 5.24729752 7.03067833]
 [6.76708264 8.50696245 5.85149236]]


In [29]:
#14.create a normalized form of iri's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
sepal_length = iris.data[: ,0]
min_val = np.min(sepal_length)
max_val=np.max(sepal_length)
normalized_sepal_length =(sepal_length - min_val) / (max_val - min_val)
print(normalized_sepal_length)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [ ]:
#